apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: mcp-treeofthoughts-pdb
  namespace: mcp-treeofthoughts
  labels:
    app: mcp-treeofthoughts
spec:
  minAvailable: 1
  selector:
    matchLabels:
      app: mcp-treeofthoughts
      component: server

---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: mcp-treeofthoughts-hpa
  namespace: mcp-treeofthoughts
  labels:
    app: mcp-treeofthoughts
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: StatefulSet
    name: mcp-treeofthoughts
  minReplicas: 1
  maxReplicas: 5
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 70
    - type: Resource
      resource:
        name: memory
        target:
          type: Utilization
          averageUtilization: 80
  behavior:
    scaleDown:
      stabilizationWindowSeconds: 300
      policies:
        - type: Percent
          value: 50
          periodSeconds: 60
    scaleUp:
      stabilizationWindowSeconds: 30
      policies:
        - type: Percent
          value: 100
          periodSeconds: 15
