apiVersion: v1
kind: Namespace
metadata:
  name: mcp-treeofthoughts
  labels:
    app: mcp-treeofthoughts
    security: enterprise
    version: "1.0"
---
apiVersion: v1
kind: ResourceQuota
metadata:
  name: mcp-resource-quota
  namespace: mcp-treeofthoughts
spec:
  hard:
    requests.cpu: "2"
    requests.memory: 4Gi
    limits.cpu: "4"
    limits.memory: 8Gi
    pods: "10"
    services: "5"
    secrets: "10"
    configmaps: "10"
---
apiVersion: v1
kind: LimitRange
metadata:
  name: mcp-limit-range
  namespace: mcp-treeofthoughts
spec:
  limits:
    - default:
        cpu: 500m
        memory: 1Gi
      defaultRequest:
        cpu: 100m
        memory: 256Mi
      type: Container
