apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: mcp-treeofthoughts
  namespace: mcp-treeofthoughts
  labels:
    app: mcp-treeofthoughts
    component: server
spec:
  serviceName: "mcp-treeofthoughts-headless"
  replicas: 1
  selector:
    matchLabels:
      app: mcp-treeofthoughts
      component: server
  template:
    metadata:
      labels:
        app: mcp-treeofthoughts
        component: server
        security.istio.io/tlsMode: istio
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "8080"
        prometheus.io/path: "/metrics"
    spec:
      serviceAccountName: mcp-treeofthoughts-sa
      securityContext:
        runAsNonRoot: true
        runAsUser: 1001
        runAsGroup: 1001
        fsGroup: 1001
      containers:
        - name: mcp-server
          image: mcp-treeofthoughts:latest # Replace with actual image
          imagePullPolicy: Always
          ports:
            - containerPort: 5173
              name: http
              protocol: TCP
            - containerPort: 8080
              name: metrics
              protocol: TCP
          env:
            # Configuration from ConfigMap
            - name: JWT_ALGORITHM
              valueFrom:
                configMapKeyRef:
                  name: mcp-treeofthoughts-config
                  key: JWT_ALGORITHM
            - name: JWT_EXPIRATION_HOURS
              valueFrom:
                configMapKeyRef:
                  name: mcp-treeofthoughts-config
                  key: JWT_EXPIRATION_HOURS
            - name: JWT_ISSUER
              valueFrom:
                configMapKeyRef:
                  name: mcp-treeofthoughts-config
                  key: JWT_ISSUER
            - name: JWT_AUDIENCE
              valueFrom:
                configMapKeyRef:
                  name: mcp-treeofthoughts-config
                  key: JWT_AUDIENCE
            - name: KEY_ROTATION_HOURS
              valueFrom:
                configMapKeyRef:
                  name: mcp-treeofthoughts-config
                  key: KEY_ROTATION_HOURS
            - name: SERVER_HOST
              valueFrom:
                configMapKeyRef:
                  name: mcp-treeofthoughts-config
                  key: SERVER_HOST
            - name: SERVER_PORT
              valueFrom:
                configMapKeyRef:
                  name: mcp-treeofthoughts-config
                  key: SERVER_PORT
            - name: LOG_LEVEL
              valueFrom:
                configMapKeyRef:
                  name: mcp-treeofthoughts-config
                  key: LOG_LEVEL

            # Secrets
            - name: PRIVATE_KEY_PATH
              value: "/etc/mcp/keys/private-key"

            # Pod Information
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: POD_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: POD_IP
              valueFrom:
                fieldRef:
                  fieldPath: status.podIP

          volumeMounts:
            - name: private-key
              mountPath: /etc/mcp/keys
              readOnly: true
            - name: data
              mountPath: /data
            - name: tmp
              mountPath: /tmp

          resources:
            requests:
              cpu: 200m
              memory: 512Mi
            limits:
              cpu: 1000m
              memory: 2Gi

          livenessProbe:
            httpGet:
              path: /health
              port: http
            initialDelaySeconds: 30
            periodSeconds: 10
            timeoutSeconds: 5
            failureThreshold: 3

          readinessProbe:
            httpGet:
              path: /health
              port: http
            initialDelaySeconds: 5
            periodSeconds: 5
            timeoutSeconds: 3
            failureThreshold: 3

          startupProbe:
            httpGet:
              path: /health
              port: http
            initialDelaySeconds: 10
            periodSeconds: 10
            timeoutSeconds: 5
            failureThreshold: 30

          securityContext:
            allowPrivilegeEscalation: false
            readOnlyRootFilesystem: true
            capabilities:
              drop:
                - ALL

      volumes:
        - name: private-key
          secret:
            secretName: mcp-treeofthoughts-secrets
            items:
              - key: private-key
                path: private-key
            defaultMode: 0400
        - name: tmp
          emptyDir: {}

      imagePullSecrets:
        - name: mcp-registry-secret

      terminationGracePeriodSeconds: 30

      affinity:
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
            - weight: 100
              podAffinityTerm:
                labelSelector:
                  matchExpressions:
                    - key: app
                      operator: In
                      values:
                        - mcp-treeofthoughts
                topologyKey: kubernetes.io/hostname

  volumeClaimTemplates:
    - metadata:
        name: data
        labels:
          app: mcp-treeofthoughts
      spec:
        accessModes: ["ReadWriteOnce"]
        resources:
          requests:
            storage: 10Gi
        storageClassName: fast-ssd # Adjust based on your cluster
