name: E2E Authentication Tests

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main, develop ]

jobs:
  e2e-auth-tests:
    runs-on: ubuntu-latest

    steps:

    - name: Generate RSA key pair for JWT
      run: |
        mkdir -p /tmp/jwt_keys
        openssl genpkey -algorithm RSA -out /tmp/jwt_keys/private_key.pem -pkcs8
        chmod 600 /tmp/jwt_keys/private_key.pem
        echo "PRIVATE_KEY_PATH=/tmp/jwt_keys/private_key.pem" >> $GITHUB_ENV

    - name: Install system dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y openssl

    - name: Install FastMCP and test dependencies
      run: |
        pip install "fastmcp[all]>=0.6.0"
        pip install pytest pytest-asyncio requests cryptography pyjwt

    - name: Verify FastMCP installation
      run: |
        python -c "import fastmcp; print(f'FastMCP version: {fastmcp.__version__}')"

    - name: Set environment variables for tests
      run: |
        echo "FASTMCP_CLOUD=true" >> $GITHUB_ENV

    - name: Run E2E Authentication Tests
      env:
        FASTMCP_CLOUD: "true"
        PRIVATE_KEY_PATH: ${{ env.PRIVATE_KEY_PATH }}
        AUTH_TOKEN: ${{ secrets.E2E_AUTH_TOKEN }}
        FASTMCP_SERVER_AUTH: ${{ secrets.FASTMCP_SERVER_AUTH }}
      run: |
        python scripts/run_e2e_auth_tests.py --verbose

    - name: Run Pytest Test Suite
      env:
        FASTMCP_CLOUD: "true"
        PRIVATE_KEY_PATH: ${{ env.PRIVATE_KEY_PATH }}
        AUTH_TOKEN: ${{ secrets.E2E_AUTH_TOKEN }}
        FASTMCP_SERVER_AUTH: ${{ secrets.FASTMCP_SERVER_AUTH }}
      run: |
        python -m pytest src/tests/test_e2e_authentication.py -v --tb=short

    - name: Upload test results
      if: always()
      uses: actions/upload-artifact@v3
      with:
        name: e2e-test-results
        path: |
          logs/
          *.log
        retention-days: 7

    - name: Test Cloud Connectivity
      if: env.AUTH_TOKEN != ''
      env:
        AUTH_TOKEN: ${{ secrets.E2E_AUTH_TOKEN }}
      run: |
        curl -H "Authorization: Bearer " \
             -H "Content-Type: application/json" \
             https://mcptreeofthoughts.fastmcp.app/mcp \
             --max-time 30 \
             --fail-with-body || echo "Cloud connectivity test completed"

