name: E2E Authentication Tests

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main, develop ]

jobs:
  e2e-auth-tests:
    runs-on: ubuntu-latest
    timeout-minutes: 15

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: 3.12

    - name: Install system dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y openssl

    - name: Install Python dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Install FastMCP and test dependencies
      run: |
        pip install "fastmcp[all]>=0.6.0"
        pip install pytest pytest-asyncio requests cryptography pyjwt

    - name: Verify FastMCP installation
      run: |
        python -c "import fastmcp; print(f'FastMCP version: {fastmcp.__version__}')"

    - name: Generate RSA key pair for JWT
      run: |
        mkdir -p /tmp/jwt_keys
        openssl genpkey -algorithm RSA -out /tmp/jwt_keys/private_key.pem -pkeyopt rsa_keygen_bits:2048
        chmod 600 /tmp/jwt_keys/private_key.pem
        ls -la /tmp/jwt_keys/private_key.pem
        echo "PRIVATE_KEY_PATH=/tmp/jwt_keys/private_key.pem" >> $GITHUB_ENV

    - name: Verify key generation
      run: |
        echo "PRIVATE_KEY_PATH: /tmp/jwt_keys/private_key.pem"
        ls -la /tmp/jwt_keys/private_key.pem
        openssl rsa -in /tmp/jwt_keys/private_key.pem -check -noout

    - name: Set environment variables
      run: |
        echo "FASTMCP_CLOUD=true" >> $GITHUB_ENV
        echo "CI=true" >> $GITHUB_ENV

    - name: Run E2E Tests
      env:
        FASTMCP_CLOUD: "true"
        PRIVATE_KEY_PATH: /tmp/jwt_keys/private_key.pem
        CI: "true"
      run: |
        python scripts/run_e2e_auth_tests.py --verbose

    - name: Run Pytest Suite
      env:
        FASTMCP_CLOUD: "true"
        PRIVATE_KEY_PATH: /tmp/jwt_keys/private_key.pem
        CI: "true"
      run: |
        python -m pytest src/tests/test_e2e_authentication.py -v --tb=short -s


